include: package:very_good_analysis/analysis_options.3.1.0.yaml

linter:
  rules:
    public_member_api_docs: false
    require_trailing_commas: false
    flutter_style_todos: false
    use_build_context_synchronously: false

analyzer:
  exclude:
    - lib/firebase_options.dart
    - '**/*.freezed.dart'
    - '**/*.g.dart'
