name: creative_minds
description: Social media app for creative minds.
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: 3.3.3

dependencies:
  cloud_firestore: ^3.5.1
  firebase_auth: ^3.11.2
  firebase_core: ^1.24.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.5+1
  flutter_riverpod: ^2.0.2
  freezed_annotation: ^2.2.0
  hooks_riverpod: ^2.0.2
  json_annotation: ^4.7.0

dev_dependencies:
  build_runner: ^2.3.0
  flutter_test:
    sdk: flutter
  freezed: ^2.2.0
  json_serializable: ^6.5.1
  very_good_analysis: ^3.1.0

flutter:
  uses-material-design: true
