// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrxoZ1wYTWmqD4M4pSuFIIRjVTdR7fMk4',
    appId: '1:126559713443:web:74fbcf27e677d5a6ace716',
    messagingSenderId: '126559713443',
    projectId: 'creative-minds-cm',
    authDomain: 'creative-minds-cm.firebaseapp.com',
    storageBucket: 'creative-minds-cm.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCp9OIsMLWnJbiZu-iv2SGDOzbAfw-Z6Bk',
    appId: '1:126559713443:android:8b6162f11fbf7cecace716',
    messagingSenderId: '126559713443',
    projectId: 'creative-minds-cm',
    storageBucket: 'creative-minds-cm.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZTaPbylP8AxV748DE3UJRc4-PJqv_fFA',
    appId: '1:126559713443:ios:2760ecb2f8bd48dface716',
    messagingSenderId: '126559713443',
    projectId: 'creative-minds-cm',
    storageBucket: 'creative-minds-cm.appspot.com',
    iosClientId: '126559713443-i08ci3r9ohkrlq8jjeaqjctt1cuin06e.apps.googleusercontent.com',
    iosBundleId: 'com.wojtekoziol.creative-minds',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZTaPbylP8AxV748DE3UJRc4-PJqv_fFA',
    appId: '1:126559713443:ios:579f38765331cd91ace716',
    messagingSenderId: '126559713443',
    projectId: 'creative-minds-cm',
    storageBucket: 'creative-minds-cm.appspot.com',
    iosClientId: '126559713443-q931bura610bfdtlopgnpfotgd5o1k9f.apps.googleusercontent.com',
    iosBundleId: 'com.wojtekoziol.creativeMinds',
  );
}
